//////////////////////////////////////////////////////////////////////////////
//    Copyright 2004-2007, SenseGraphics AB
//
//    This file is part of H3D API.
//
//    H3D API is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    H3D API is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with H3D API; if not, write to the Free Software
//    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//
//    A commercial license is also available. Please contact us at 
//    www.sensegraphics.com for more information.
//
//
/// \file HAPIHapticsDevice.cpp
/// \brief Cpp file for HAPIHapticsDevice.
///
//
//////////////////////////////////////////////////////////////////////////////

#include <HAPI/HAPIHapticsDevice.h>

using namespace HAPI;

HAPIHapticsDevice::local_auto_ptr< 
    list< HAPIHapticsDevice::HapticsDeviceRegistration > 
  > HAPIHapticsDevice::registered_devices( NULL );
 
bool HAPIHapticsDevice::initialized = false; 

H3DUtil::PeriodicThread::CallbackCode
  HAPIHapticsDevice::transferObjectsCallback( 
  void *data ) {
  HAPIHapticsDevice *hd = 
    static_cast< HAPIHapticsDevice * >( data );
  hd->current_shapes = hd->tmp_shapes;
  return H3DUtil::PeriodicThread::CALLBACK_DONE;
}

// Callback function for rendering force effects on the 
// HLHapticsDevice.  
H3DUtil::PeriodicThread::CallbackCode
  HAPIHapticsDevice::hapticRenderingCallback( void *data ) {


  HAPIHapticsDevice *hd = 
    static_cast< HAPIHapticsDevice * >( data );
  if( hd->nr_haptics_loops > 100 ) {
    TimeStamp now = TimeStamp();
    unsigned int nr_loops = hd->nr_haptics_loops;
    hd->nr_haptics_loops = 0;
    TimeStamp dt = now - hd->last_hr_update;
    hd->haptics_rate = (unsigned int)( nr_loops / dt );
    hd->last_hr_update = now;
  }
  hd->nr_haptics_loops++;
  
  TimeStamp start_time = TimeStamp();
  TimeStamp dt = start_time - hd->last_loop_time;
  hd->last_loop_time = start_time;

  hd->updateDeviceValues( dt );
  
  HAPIForceEffect::EffectOutput output;
  
  hd->force_effect_lock.lock();
  bool last_add_interpolate = !hd->last_add_rem_effect_map.empty();
  bool current_add_interpolate = !hd->current_add_rem_effect_map.empty();
  if( hd->switching_effects || current_add_interpolate ||
      last_add_interpolate ) {
    // If there is any kind of interpolation needed to be done, it is taken
    // care of here.

    // If any force effect should be removed from last_force_effect it is
    // stored here. Only used if last_add_interpolate is true.
    list< HAPIForceEffect * > to_remove;
    TimeStamp now_time;

    // calculate the forces generated by the last active force effects.
    if( last_add_interpolate ) {
      int j = 0;
      int shift_index = 0;
      // If any of the forces should be phased in or out then
      // check it, if it should be removed remove it and update index
      // in the map last_add_rem_effect_map.
      for( HapticEffectVector::const_iterator i =
             hd->last_force_effects.begin();
           i != hd->last_force_effects.end();
           i++, j++ ) {
        IndexTimeMap::iterator found = hd->last_add_rem_effect_map.find( j );
        if( found != hd->last_add_rem_effect_map.end() ) {
          HAPIFloat temp_fraction = (*found).second.getFraction( now_time );
          if( temp_fraction > 1 ) temp_fraction = 1;
          if( temp_fraction < 0 ) {
            hd->last_add_rem_effect_map.erase( found );
            to_remove.push_back( *i );
            shift_index++;
          } else {
            if ( shift_index > 0 ) {
              hd->last_add_rem_effect_map[ j - shift_index ] =
                hd->last_add_rem_effect_map[ j ];
              hd->last_add_rem_effect_map.erase( j );
            }
            output = output + (*i)->calculateForces( hd, dt ) * temp_fraction;
          }
        } else {
          output = output + (*i)->calculateForces( hd, dt );
        }
      }
    } else {
      // calculate forces normally.
      for( HapticEffectVector::const_iterator i =
           hd->last_force_effects.begin();
         i != hd->last_force_effects.end();
         i++ ) {
        output = output + (*i)->calculateForces( hd, dt );
      }
    }

    // fraction used for interpolation
    HAPIFloat force_interpolation_fraction = 1;

    if( hd->switching_effects ) {
      force_interpolation_fraction =
        ( now_time - hd->last_force_effect_change ) /
        hd->switch_effects_duration;
      if( force_interpolation_fraction > 1 ) {
        force_interpolation_fraction = 1;
        hd->last_force_effects.clear();
        hd->last_add_rem_effect_map.clear();
        hd->switching_effects = false;
      }
      output = output * ( 1 - force_interpolation_fraction );
    }

    if( !hd->last_force_effects.empty() ) {
      // remove HAPIForceEffects from last_force_effects if they have been
      // phased out.
      for( list< HAPIForceEffect * >::iterator i = to_remove.begin();
           i != to_remove.end();
           i++ ) {
        hd->last_force_effects.erase( *i );
      }
    }

    // calculate the forces generated by the active force effects
    if( current_add_interpolate ) {
      // If there are force effects that should be phased in
      // a fraction will be calculated.
      int j = 0;
      for( HapticEffectVector::const_iterator i =
             hd->current_force_effects.begin();
           i != hd->current_force_effects.end();
           i++, j++ ) {
        IndexTimeMap::iterator found =
          hd->current_add_rem_effect_map.find( j );
        if( found != hd->current_add_rem_effect_map.end() ) {
          HAPIFloat temp_fraction =
            hd->current_add_rem_effect_map[j].getFraction( now_time );
          if( temp_fraction > 1 ) {
            temp_fraction = 1;
            hd->current_add_rem_effect_map.erase( found );
          }
          output = output + (*i)->calculateForces( hd, dt ) *
                            temp_fraction *
                            force_interpolation_fraction;
        } else
          output = output + (*i)->calculateForces( hd, dt ) *
                            force_interpolation_fraction;
      }
    } else {
      // Only fraction calculations from setEffects and swapEffects.
      for( HapticEffectVector::const_iterator i =
           hd->current_force_effects.begin();
         i != hd->current_force_effects.end();
         i++ ) {
        output = output + (*i)->calculateForces( hd, dt )
          * force_interpolation_fraction;
      }
    }
  } else {
    // No interpolation what so ever, just calculate and sum the forces
    // from the haptic effects.
    for( HapticEffectVector::const_iterator i =
           hd->current_force_effects.begin();
         i != hd->current_force_effects.end();
         i++ ) {
      output = output + (*i)->calculateForces( hd, dt );
    }
  }
  hd->force_effect_lock.unlock();

  hd->renderer_change_lock.lock();

  for( unsigned int s = 0; s < hd->haptics_renderers.size(); s++ ) {
    if( hd->haptics_renderers[s] && s < hd->current_shapes.size() ) {
      output = output + 
        hd->haptics_renderers[s]->
          renderHapticsOneStep( hd, hd->current_shapes[s] );
    }
  }

  hd->renderer_change_lock.unlock();

  // add the resulting force and torque to the rendered force.
  hd->sendForce( output.force );
  hd->sendTorque( output.torque );

  hd->sendOutput();

  hd->time_in_last_loop = TimeStamp() - start_time;

  if( hd->device_state == UNINITIALIZED )
    return H3DUtil::PeriodicThread::CALLBACK_DONE;
  else
    return H3DUtil::PeriodicThread::CALLBACK_CONTINUE;
}

void HAPIHapticsDevice::transferObjects() {
  if( thread ) {
    for( unsigned int s = 0; s < haptics_renderers.size(); s++ ) {
      if( haptics_renderers[s] && s < tmp_shapes.size() ) {
         haptics_renderers[s]->preProcessShapes( this, tmp_shapes[s] );
      }
    }
    thread->synchronousCallback( transferObjectsCallback,
                                 this );

  }
}


HAPIHapticsDevice::ErrorCode HAPIHapticsDevice::initDevice() {
  if( device_state == UNINITIALIZED ) {
    last_device_values = current_device_values = DeviceValues();
    last_raw_device_values = current_raw_device_values = DeviceValues();
    if( !initHapticsDevice() ) {
      return FAIL;
    }
    device_state = INITIALIZED;
    for( unsigned int i = 0; i < haptics_renderers.size(); i++ ) {
      if( haptics_renderers[i] ) {
        haptics_renderers[i]->initRenderer( this );
      }
    }
    
    device_state = INITIALIZED;
    if( !thread ) {
          // create a new thread to run the haptics in
#ifdef WIN32
     thread = new H3DUtil::HapticThread(  THREAD_PRIORITY_ABOVE_NORMAL, 1000 );
#else
      thread = new H3DUtil::HapticThread( 20, 1000 );
#endif
      delete_thread = true;
    }
    if( setup_haptic_rendering_callback ) {
      thread->asynchronousCallback( hapticRenderingCallback,
                                    this );
    }
    
  }
  return SUCCESS;
}

void HAPIHapticsDevice::updateDeviceValues( HAPITime dt ) {
  if( device_state == ENABLED ) {
    DeviceValues dv;
    updateDeviceValues( dv, dt );
    
    device_values_lock.lock();
    last_device_values = current_device_values;
    last_raw_device_values = current_raw_device_values;
    current_raw_device_values = dv;

    current_device_values.position = position_calibration * dv.position;
    
    current_device_values.velocity = 
      position_calibration.getScaleRotationPart() * dv.velocity;
    current_device_values.orientation = 
      orientation_calibration * dv.orientation;
    current_device_values.force = 
      position_calibration.getScaleRotationPart() * dv.force;
    current_device_values.torque = 
      position_calibration.getScaleRotationPart() * dv.torque;
    device_values_lock.unlock();
  } else {
    if( device_state == INITIALIZED ) {
      device_values_lock.lock();
      last_device_values = current_device_values;
      last_raw_device_values = current_raw_device_values;
      device_values_lock.unlock();
    }
  }
}
